// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtkoenqyxptijpacpxdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0a29lbnF5eHB0aWpwYWNweGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1ODA4NTUsImV4cCI6MjA4NjE1Njg1NX0.GkpI9vD04OgSwl9LvGdUEi8-OHVojbiFzlbcO8Y9LDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});